### ISSUE TITLE
About FlexRoPE experiments

### ISSUE THREAD

**Issue by AndysonYs** [showlab/FAR#4]
Hi! Thank you for your amazing work. I have a question regarding the FlexRoPE part. Could you please provide the experiment code on FlexRoPE-PE?

**Comment by guyuchao** [comment]
Hi, we are constructing an inference demo and organizing experiment configurations. We will upload these later.

**Comment by guyuchao** [comment]
Hi, I have uploaded a Colab demo to reimplementing the findings of FlexRoPE in Figure 12. For the quantitative results in Figure 6, you can use the following config to train a 16-frame model. Then you can perform inference with different context frames. For example, by setting ```context_length: 240``` and ```unroll_length: 16```, which means 256/16 = 16x extrapolation during inference.


```yaml
name: ablation_FAR_M_minecraft_16frame_res128_200K_bs32
manual_seed: 0
mixed_precision: bf16

# dataset and data loader settings
datasets:
  train:
    type: MinecraftDataset
    data_list: datasets/minecraft_latent/minecraft_train.json
    split: training
    use_latent: true
    data_cfg:
      num_frames: 16
      frame_interval: 1
    batch_size_per_gpu: 4

  sample:
    type: MinecraftDataset
    data_list: datasets/minecraft/minecraft_val.json
    split: validation
    data_cfg:
      num_frames: 16
      frame_interval: 1
    num_sample: 256
    batch_size_per_gpu: 8

models:
  model_cfg:
    transformer:
      from_pretrained: ~ # diffusers pretrained path (from_pretrained)
      init_cfg:
        type: FAR_M
        config: {
          "condition_cfg": {
            "type": "action",
            "num_action_classes": 4
          }
        }
    vae:
      type: MyAutoencoderDC
      from_config: options/model_cfg/dcae/model_16x_c32_config.json
      from_config_pretrained: experiments/pretrained_models/FAR_Models/dcae/DCAE_Minecraft_Res128-a5677f66.pth
    scheduler:
      from_pretrained: options/model_cfg/far/scheduler_config.json
  clean_context_ratio: 0.1
  weighting_scheme: logit_normal
  training_type: long_context

# path
path:
  pretrain_network: ~

# training settings
train:
  train_pipeline: FARTrainer

  optim_g:
    type: AdamW
    lr: !!float 1e-4
    weight_decay: 0
    betas: [ 0.9, 0.999 ]

  param_names_to_optimize: ~
  ema_decay: 0.9999

  lr_scheduler: constant_with_warmup
  warmup_iter: 10000
  total_iter: 200000
  max_grad_norm: 1.0

# validation settings
val:
  val_pipeline: FARPipeline
  val_freq: 50000
  sample_cfg:
    context_length: 2
    unroll_length: 14
    guidance_scale: 1.5
    num_inference_steps: 50
    sample_size: 8
    sample_trajectory_per_video: 1
    use_kv_cache: false
  eval_cfg:
    metrics: ['mse', 'psnr', 'ssim', 'fvd', 'lpips']

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 50000
  use_wandb: false
```
